before_script:
- gem install cid
script:
- cid validate
after_success:
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  cid publish'
env:
  global:
    secure: HiB6A0WmZdr7oXn9NKUnkW8Qh8UmE2yJdY4ZQW/IalCnQzkcvj6UCPsFJiJYUxGuNUy/Tvqtqh5jKuVqHw5JmzYW/S2/9SQy3A5v1QxnHp2wrKo6Oe5sOH8K5PHMpO4sqLwh1EpQ49tMJQd9G42A5ZJRCAmQMKgvukN1wSVGiJQ=
